### ISSUE TITLE
Error: Bridge contract constructor expected 1 arguments, received 0

### ISSUE THREAD

**Issue by lazaridiscom** [GridPlus/cryptobridge-contracts#17]
(affect #11)
Windows 10, bash on Windows, Hyper-V ubuntu instance.

The following error raises with `truffle test`

```sh
P:\sand\cryptobridge\contracts>truffle.cmd test
0xf399c77f9a403c541bbac8dae1e016bf942f09f5
Using network 'development'.

Error: Bridge contract constructor expected 1 arguments, received 0
    at C:\Users\laz\AppData\Roaming\npm\node_modules\truffle-core\node_modules\truffle-contract\contract.js:388:19
    at new Promise (<anonymous>)
    at C:\Users\laz\AppData\Roaming\npm\node_modules\truffle-core\node_modules\truffle-contract\contract.js:372:16
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Truffle "hijacks" the test-system, so it is not obvious how to debug this using a standard IDE debugging setup.

Additionally there is no log-file produced.

Please verify that the existent code actually works as-is on your side, thus additional setup/debugging effort is avoided.

**Comment by lazaridiscom** [comment]
the `--verbose-rpc` output [test.log](https://github.com/GridPlus/cryptobridge-contracts/files/1747996/test.log)

**Comment by lazaridiscom** [comment]
Some information here: https://github.com/trufflesuite/truffle/issues/596

I've changed to truffle 4.0.0 and it seems to be working now.

**Comment by alex-miller-0** [comment]
Never had that problem, but I believe I have been on truffle 4.0.1 for the entirety of developing this.

Did not realize older version break instantiation like that...

**Comment by lazaridiscom** [comment]
There's actually a bug in the code (constructor argument not passed), here:

https://github.com/GridPlus/cryptobridge-contracts/commit/22a26ae31aab7d55755a5711cd628770b8623ddb#diff-d7ea30ad9c8564ba259bdb799f53fd17R33

The bug is conditionally triggered, depending on truffle version. Pure hell.

**Comment by lazaridiscom** [comment]
> Did not realize older version break instantiation like that...

The latest 4.0.6 breaks it
