### ISSUE TITLE
Update Project Resources

### ISSUE THREAD

**Issue by lazaridiscom** [GridPlus/cryptobridge-contracts#20]
Work on issue #11 has brought up multiple issues, mainly with documentation, dev-system-setup, and some more or less hidden bugs.

The work on this issues was/is beyond the scope of #11, yet it is important that this work is done. This is a prioritized/sequenced list:

- [ ] Provide a Docker Image
- [ ] Provide Windows Support (minimum: Win10 Pro/Docker)
- [ ] Update Project Docs
    - [ ] Provide concise installation steps for (starting with "Prerequisites node.js" etc.), ideal a cli-sequence
    - [ ] Provide the additional steps for contributing(!) developers
    - [ ] Provide installation remarks re Windows
    - [ ] low priority: reduce size of readme.
- [ ] Update Test System
    - [ ] Split down larger test files into separate files
    - [ ] Separate unit and integration tests
    - [ ] Provide Mock and Real Integration test
- [ ] Upgrade to Latest Libraries (e.g. BytesLib.sol) 
- [X] #15 - IPC Error (Already solved)
- [X] #17 - Constructor Error (Already solved)

**Comment by ghost** [comment]
closing, due to inactivity
